### ISSUE TITLE
Smaller boards

### ISSUE THREAD

**Issue by GabrielPereyra** [iartarisi/goboard.js#1]
Is there a way to display smaller boards?

**Comment by iartarisi** [comment]
Hey.

I haven't looked at this repo in a while, but it shouldn't be too hard. Most of the dimensions you can specify when creating the board. See [goboard.cljs](https://github.com/mapleoin/goboard.js/blob/master/src/goboard.cljs), you'll also have to change some other hardcoded values here and there e.g. `draw-dots` in `goban.cljs` which draws the hoshi. 

Let me know how it goes!
